#FROM python:3.8
#
## 環境変数を設定してPythonが標準出力にログを出力するようにする
#ENV PYTHONUNBUFFERED=1
#
## 作業ディレクトリを設定
#WORKDIR /app
#
## 依存関係をインストール
#COPY requirements.txt /app/
#RUN pip install --no-cache-dir -r requirements.txt
#
## プロジェクトをコピー
#COPY . /app/