version: '3'

services:
#  web:
#    image: nginx:latest
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "8080:80"
#    depends_on:
#      - django

#  db:
#    image: postgres:latest
#    environment:
#      POSTGRES_DB: mydatabase
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: password

  django:
    image: mydjango:v1
    working_dir: /app
    volumes:
      - ./hoge:/app
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'True'
#      DJANGO_DB_HOST: db
#    depends_on:
#      - db